apodiscounter:
  url: https://www.apodiscounter.de/partnerprogramme/krn.csv
  format: csv
  productIdColumnName: PZN
  priceColumnName: Preis

bodfeld:
  url: https://www.bodfeld-apotheke.de/kairion/itemfeed.txt
  format: txt
  separator: '	'
  productIdColumnName: id
  priceColumnName: price
